# Generated by Django 5.2.8 on 2025-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0009_remove_order_course_instance_order_cart_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_instance',
        ),
        migrations.AddField(
            model_name='order',
            name='course_instance',
            field=models.ManyToManyField(related_name='order', to='instructorApp.course'),
        ),
    ]
